services:

  postgresql:
    image: 'postgres'
    restart: always
    volumes:
      - postgresql-volume:/postgresql/data/recons
    ports:
      - "5432:5432"
    command: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Pa55w0rd
      POSTGRES_DB: recons
    networks:
      - recons-network

volumes:
  postgresql-volume:

networks:
  recons-network:
    driver: bridge